# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'combustionchamberMNUOJi.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFrame,
    QLCDNumber, QLabel, QPlainTextEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1229, 721)
        self.mfcAgas = QComboBox(Dialog)
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.addItem("")
        self.mfcAgas.setObjectName(u"mfcAgas")
        self.mfcAgas.setGeometry(QRect(70, 60, 81, 21))
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 10, 91, 31))
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 60, 49, 16))
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 100, 49, 16))
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 140, 49, 16))
        self.mfcBgas = QComboBox(Dialog)
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.addItem("")
        self.mfcBgas.setObjectName(u"mfcBgas")
        self.mfcBgas.setGeometry(QRect(70, 100, 81, 21))
        self.mfcCgas = QComboBox(Dialog)
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.addItem("")
        self.mfcCgas.setObjectName(u"mfcCgas")
        self.mfcCgas.setGeometry(QRect(70, 140, 81, 21))
        self.line_2 = QFrame(Dialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-10, 300, 1261, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.mfcDgas = QComboBox(Dialog)
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.addItem("")
        self.mfcDgas.setObjectName(u"mfcDgas")
        self.mfcDgas.setGeometry(QRect(70, 180, 81, 21))
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 180, 49, 16))
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(450, 60, 111, 16))
        self.openS1 = QPushButton(Dialog)
        self.openS1.setObjectName(u"openS1")
        self.openS1.setGeometry(QRect(590, 60, 75, 24))
        self.closeS1 = QPushButton(Dialog)
        self.closeS1.setObjectName(u"closeS1")
        self.closeS1.setGeometry(QRect(670, 60, 75, 24))
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(480, 110, 81, 16))
        self.closeS2 = QPushButton(Dialog)
        self.closeS2.setObjectName(u"closeS2")
        self.closeS2.setGeometry(QRect(670, 110, 75, 24))
        self.openS2 = QPushButton(Dialog)
        self.openS2.setObjectName(u"openS2")
        self.openS2.setGeometry(QRect(590, 110, 75, 24))
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(390, 160, 161, 16))
        self.closeS3 = QPushButton(Dialog)
        self.closeS3.setObjectName(u"closeS3")
        self.closeS3.setGeometry(QRect(670, 160, 75, 24))
        self.openS3 = QPushButton(Dialog)
        self.openS3.setObjectName(u"openS3")
        self.openS3.setGeometry(QRect(590, 160, 75, 24))
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(440, 210, 121, 16))
        self.openS4 = QPushButton(Dialog)
        self.openS4.setObjectName(u"openS4")
        self.openS4.setGeometry(QRect(590, 210, 75, 24))
        self.closeS4 = QPushButton(Dialog)
        self.closeS4.setObjectName(u"closeS4")
        self.closeS4.setGeometry(QRect(670, 210, 75, 24))
        self.closeS5 = QPushButton(Dialog)
        self.closeS5.setObjectName(u"closeS5")
        self.closeS5.setGeometry(QRect(1060, 60, 75, 24))
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(790, 60, 171, 16))
        self.openS5 = QPushButton(Dialog)
        self.openS5.setObjectName(u"openS5")
        self.openS5.setGeometry(QRect(980, 60, 75, 24))
        self.closeS7 = QPushButton(Dialog)
        self.closeS7.setObjectName(u"closeS7")
        self.closeS7.setGeometry(QRect(1060, 110, 75, 24))
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(830, 110, 131, 16))
        self.openS6 = QPushButton(Dialog)
        self.openS6.setObjectName(u"openS6")
        self.openS6.setGeometry(QRect(980, 110, 75, 24))
        self.closeS7_2 = QPushButton(Dialog)
        self.closeS7_2.setObjectName(u"closeS7_2")
        self.closeS7_2.setGeometry(QRect(1060, 160, 75, 24))
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(870, 160, 81, 16))
        self.openS7 = QPushButton(Dialog)
        self.openS7.setObjectName(u"openS7")
        self.openS7.setGeometry(QRect(980, 160, 75, 24))
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(170, 60, 49, 16))
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(170, 100, 49, 16))
        self.label_15 = QLabel(Dialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(170, 140, 49, 16))
        self.label_16 = QLabel(Dialog)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(170, 180, 49, 16))
        self.mfcAsetpoint = QPlainTextEdit(Dialog)
        self.mfcAsetpoint.setObjectName(u"mfcAsetpoint")
        self.mfcAsetpoint.setGeometry(QRect(230, 60, 51, 21))
        self.mfcBsetpoint = QPlainTextEdit(Dialog)
        self.mfcBsetpoint.setObjectName(u"mfcBsetpoint")
        self.mfcBsetpoint.setGeometry(QRect(230, 100, 51, 21))
        self.mfcCsetpoint = QPlainTextEdit(Dialog)
        self.mfcCsetpoint.setObjectName(u"mfcCsetpoint")
        self.mfcCsetpoint.setGeometry(QRect(230, 140, 51, 21))
        self.mfcDsetpoint = QPlainTextEdit(Dialog)
        self.mfcDsetpoint.setObjectName(u"mfcDsetpoint")
        self.mfcDsetpoint.setGeometry(QRect(230, 180, 51, 21))
        self.label_17 = QLabel(Dialog)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(310, 60, 49, 16))
        self.label_18 = QLabel(Dialog)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(310, 100, 49, 16))
        self.label_19 = QLabel(Dialog)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(310, 140, 49, 16))
        self.label_20 = QLabel(Dialog)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(310, 180, 49, 16))
        self.updatesetpoints = QPushButton(Dialog)
        self.updatesetpoints.setObjectName(u"updatesetpoints")
        self.updatesetpoints.setGeometry(QRect(130, 230, 111, 24))
        self.updatesetpoints.setCheckable(False)
        self.resetmfc = QPushButton(Dialog)
        self.resetmfc.setObjectName(u"resetmfc")
        self.resetmfc.setGeometry(QRect(130, 270, 111, 24))
        self.label_21 = QLabel(Dialog)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(740, 10, 91, 31))
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(350, -10, 61, 741))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.Lowfreqpressure = QLCDNumber(Dialog)
        self.Lowfreqpressure.setObjectName(u"Lowfreqpressure")
        self.Lowfreqpressure.setGeometry(QRect(170, 420, 81, 31))
        self.Highfreqpressure = QLCDNumber(Dialog)
        self.Highfreqpressure.setObjectName(u"Highfreqpressure")
        self.Highfreqpressure.setGeometry(QRect(170, 540, 81, 31))
        self.label_22 = QLabel(Dialog)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(80, 410, 81, 41))
        self.label_23 = QLabel(Dialog)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(60, 530, 101, 41))
        self.label_24 = QLabel(Dialog)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(140, 350, 101, 16))
        self.line_3 = QFrame(Dialog)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(910, 310, 61, 421))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.testautomation = QPushButton(Dialog)
        self.testautomation.setObjectName(u"testautomation")
        self.testautomation.setGeometry(QRect(1020, 390, 151, 61))
        self.purge = QPushButton(Dialog)
        self.purge.setObjectName(u"purge")
        self.purge.setGeometry(QRect(1020, 530, 151, 61))
        self.line.raise_()
        self.mfcAgas.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.mfcBgas.raise_()
        self.mfcCgas.raise_()
        self.line_2.raise_()
        self.mfcDgas.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.openS1.raise_()
        self.closeS1.raise_()
        self.label_7.raise_()
        self.closeS2.raise_()
        self.openS2.raise_()
        self.label_8.raise_()
        self.closeS3.raise_()
        self.openS3.raise_()
        self.label_9.raise_()
        self.openS4.raise_()
        self.closeS4.raise_()
        self.closeS5.raise_()
        self.label_10.raise_()
        self.openS5.raise_()
        self.closeS7.raise_()
        self.label_11.raise_()
        self.openS6.raise_()
        self.closeS7_2.raise_()
        self.label_12.raise_()
        self.openS7.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.mfcAsetpoint.raise_()
        self.mfcBsetpoint.raise_()
        self.mfcCsetpoint.raise_()
        self.mfcDsetpoint.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.updatesetpoints.raise_()
        self.resetmfc.raise_()
        self.label_21.raise_()
        self.Lowfreqpressure.raise_()
        self.Highfreqpressure.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.line_3.raise_()
        self.testautomation.raise_()
        self.purge.raise_()

        self.retranslateUi(Dialog)

        self.openS1.setDefault(False)
        self.closeS1.setDefault(True)
        self.closeS2.setDefault(True)
        self.closeS3.setDefault(True)
        self.openS4.setDefault(True)
        self.closeS5.setDefault(True)
        self.openS6.setDefault(True)
        self.closeS7_2.setDefault(True)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.mfcAgas.setItemText(0, QCoreApplication.translate("Dialog", u"Air", None))
        self.mfcAgas.setItemText(1, QCoreApplication.translate("Dialog", u"Ar", None))
        self.mfcAgas.setItemText(2, QCoreApplication.translate("Dialog", u"CH4", None))
        self.mfcAgas.setItemText(3, QCoreApplication.translate("Dialog", u"CO", None))
        self.mfcAgas.setItemText(4, QCoreApplication.translate("Dialog", u"CO2", None))
        self.mfcAgas.setItemText(5, QCoreApplication.translate("Dialog", u"C2H6", None))
        self.mfcAgas.setItemText(6, QCoreApplication.translate("Dialog", u"H2", None))
        self.mfcAgas.setItemText(7, QCoreApplication.translate("Dialog", u"He", None))
        self.mfcAgas.setItemText(8, QCoreApplication.translate("Dialog", u"N2", None))
        self.mfcAgas.setItemText(9, QCoreApplication.translate("Dialog", u"N2O", None))
        self.mfcAgas.setItemText(10, QCoreApplication.translate("Dialog", u"Ne", None))
        self.mfcAgas.setItemText(11, QCoreApplication.translate("Dialog", u"O2", None))
        self.mfcAgas.setItemText(12, QCoreApplication.translate("Dialog", u"C3H8", None))
        self.mfcAgas.setItemText(13, QCoreApplication.translate("Dialog", u"n-C4H10", None))
        self.mfcAgas.setItemText(14, QCoreApplication.translate("Dialog", u"C2H2", None))
        self.mfcAgas.setItemText(15, QCoreApplication.translate("Dialog", u"C2H4", None))
        self.mfcAgas.setItemText(16, QCoreApplication.translate("Dialog", u"i-C2H10", None))
        self.mfcAgas.setItemText(17, QCoreApplication.translate("Dialog", u"Kr", None))
        self.mfcAgas.setItemText(18, QCoreApplication.translate("Dialog", u"Xe", None))
        self.mfcAgas.setItemText(19, QCoreApplication.translate("Dialog", u"SF6", None))
        self.mfcAgas.setItemText(20, QCoreApplication.translate("Dialog", u"C-25", None))
        self.mfcAgas.setItemText(21, QCoreApplication.translate("Dialog", u"C-10", None))
        self.mfcAgas.setItemText(22, QCoreApplication.translate("Dialog", u"C-8", None))
        self.mfcAgas.setItemText(23, QCoreApplication.translate("Dialog", u"C-2", None))
        self.mfcAgas.setItemText(24, QCoreApplication.translate("Dialog", u"C-75", None))
        self.mfcAgas.setItemText(25, QCoreApplication.translate("Dialog", u"A-75", None))
        self.mfcAgas.setItemText(26, QCoreApplication.translate("Dialog", u"A-25", None))
        self.mfcAgas.setItemText(27, QCoreApplication.translate("Dialog", u"A1025", None))
        self.mfcAgas.setItemText(28, QCoreApplication.translate("Dialog", u"Star29", None))
        self.mfcAgas.setItemText(29, QCoreApplication.translate("Dialog", u"P-5", None))

        self.label.setText(QCoreApplication.translate("Dialog", u"MFC Controllers:", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"MFC A:", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"MFC B:", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"MFC C:", None))
        self.mfcBgas.setItemText(0, QCoreApplication.translate("Dialog", u"Air", None))
        self.mfcBgas.setItemText(1, QCoreApplication.translate("Dialog", u"Ar", None))
        self.mfcBgas.setItemText(2, QCoreApplication.translate("Dialog", u"CH4", None))
        self.mfcBgas.setItemText(3, QCoreApplication.translate("Dialog", u"CO", None))
        self.mfcBgas.setItemText(4, QCoreApplication.translate("Dialog", u"CO2", None))
        self.mfcBgas.setItemText(5, QCoreApplication.translate("Dialog", u"C2H6", None))
        self.mfcBgas.setItemText(6, QCoreApplication.translate("Dialog", u"H2", None))
        self.mfcBgas.setItemText(7, QCoreApplication.translate("Dialog", u"He", None))
        self.mfcBgas.setItemText(8, QCoreApplication.translate("Dialog", u"N2", None))
        self.mfcBgas.setItemText(9, QCoreApplication.translate("Dialog", u"N2O", None))
        self.mfcBgas.setItemText(10, QCoreApplication.translate("Dialog", u"Ne", None))
        self.mfcBgas.setItemText(11, QCoreApplication.translate("Dialog", u"O2", None))
        self.mfcBgas.setItemText(12, QCoreApplication.translate("Dialog", u"C3H8", None))
        self.mfcBgas.setItemText(13, QCoreApplication.translate("Dialog", u"n-C4H10", None))
        self.mfcBgas.setItemText(14, QCoreApplication.translate("Dialog", u"C2H2", None))
        self.mfcBgas.setItemText(15, QCoreApplication.translate("Dialog", u"C2H4", None))
        self.mfcBgas.setItemText(16, QCoreApplication.translate("Dialog", u"i-C2H10", None))
        self.mfcBgas.setItemText(17, QCoreApplication.translate("Dialog", u"Kr", None))
        self.mfcBgas.setItemText(18, QCoreApplication.translate("Dialog", u"Xe", None))
        self.mfcBgas.setItemText(19, QCoreApplication.translate("Dialog", u"SF6", None))
        self.mfcBgas.setItemText(20, QCoreApplication.translate("Dialog", u"C-25", None))
        self.mfcBgas.setItemText(21, QCoreApplication.translate("Dialog", u"C-10", None))
        self.mfcBgas.setItemText(22, QCoreApplication.translate("Dialog", u"C-8", None))
        self.mfcBgas.setItemText(23, QCoreApplication.translate("Dialog", u"C-2", None))
        self.mfcBgas.setItemText(24, QCoreApplication.translate("Dialog", u"C-75", None))
        self.mfcBgas.setItemText(25, QCoreApplication.translate("Dialog", u"A-75", None))
        self.mfcBgas.setItemText(26, QCoreApplication.translate("Dialog", u"A-25", None))
        self.mfcBgas.setItemText(27, QCoreApplication.translate("Dialog", u"A1025", None))
        self.mfcBgas.setItemText(28, QCoreApplication.translate("Dialog", u"Star29", None))
        self.mfcBgas.setItemText(29, QCoreApplication.translate("Dialog", u"P-5", None))

        self.mfcCgas.setItemText(0, QCoreApplication.translate("Dialog", u"Air", None))
        self.mfcCgas.setItemText(1, QCoreApplication.translate("Dialog", u"Ar", None))
        self.mfcCgas.setItemText(2, QCoreApplication.translate("Dialog", u"CH4", None))
        self.mfcCgas.setItemText(3, QCoreApplication.translate("Dialog", u"CO", None))
        self.mfcCgas.setItemText(4, QCoreApplication.translate("Dialog", u"CO2", None))
        self.mfcCgas.setItemText(5, QCoreApplication.translate("Dialog", u"C2H6", None))
        self.mfcCgas.setItemText(6, QCoreApplication.translate("Dialog", u"H2", None))
        self.mfcCgas.setItemText(7, QCoreApplication.translate("Dialog", u"He", None))
        self.mfcCgas.setItemText(8, QCoreApplication.translate("Dialog", u"N2", None))
        self.mfcCgas.setItemText(9, QCoreApplication.translate("Dialog", u"N2O", None))
        self.mfcCgas.setItemText(10, QCoreApplication.translate("Dialog", u"Ne", None))
        self.mfcCgas.setItemText(11, QCoreApplication.translate("Dialog", u"O2", None))
        self.mfcCgas.setItemText(12, QCoreApplication.translate("Dialog", u"C3H8", None))
        self.mfcCgas.setItemText(13, QCoreApplication.translate("Dialog", u"n-C4H10", None))
        self.mfcCgas.setItemText(14, QCoreApplication.translate("Dialog", u"C2H2", None))
        self.mfcCgas.setItemText(15, QCoreApplication.translate("Dialog", u"C2H4", None))
        self.mfcCgas.setItemText(16, QCoreApplication.translate("Dialog", u"i-C2H10", None))
        self.mfcCgas.setItemText(17, QCoreApplication.translate("Dialog", u"Kr", None))
        self.mfcCgas.setItemText(18, QCoreApplication.translate("Dialog", u"Xe", None))
        self.mfcCgas.setItemText(19, QCoreApplication.translate("Dialog", u"SF6", None))
        self.mfcCgas.setItemText(20, QCoreApplication.translate("Dialog", u"C-25", None))
        self.mfcCgas.setItemText(21, QCoreApplication.translate("Dialog", u"C-10", None))
        self.mfcCgas.setItemText(22, QCoreApplication.translate("Dialog", u"C-8", None))
        self.mfcCgas.setItemText(23, QCoreApplication.translate("Dialog", u"C-2", None))
        self.mfcCgas.setItemText(24, QCoreApplication.translate("Dialog", u"C-75", None))
        self.mfcCgas.setItemText(25, QCoreApplication.translate("Dialog", u"A-75", None))
        self.mfcCgas.setItemText(26, QCoreApplication.translate("Dialog", u"A-25", None))
        self.mfcCgas.setItemText(27, QCoreApplication.translate("Dialog", u"A1025", None))
        self.mfcCgas.setItemText(28, QCoreApplication.translate("Dialog", u"Star29", None))
        self.mfcCgas.setItemText(29, QCoreApplication.translate("Dialog", u"P-5", None))

        self.mfcDgas.setItemText(0, QCoreApplication.translate("Dialog", u"Air", None))
        self.mfcDgas.setItemText(1, QCoreApplication.translate("Dialog", u"Ar", None))
        self.mfcDgas.setItemText(2, QCoreApplication.translate("Dialog", u"CH4", None))
        self.mfcDgas.setItemText(3, QCoreApplication.translate("Dialog", u"CO", None))
        self.mfcDgas.setItemText(4, QCoreApplication.translate("Dialog", u"CO2", None))
        self.mfcDgas.setItemText(5, QCoreApplication.translate("Dialog", u"C2H6", None))
        self.mfcDgas.setItemText(6, QCoreApplication.translate("Dialog", u"H2", None))
        self.mfcDgas.setItemText(7, QCoreApplication.translate("Dialog", u"He", None))
        self.mfcDgas.setItemText(8, QCoreApplication.translate("Dialog", u"N2", None))
        self.mfcDgas.setItemText(9, QCoreApplication.translate("Dialog", u"N2O", None))
        self.mfcDgas.setItemText(10, QCoreApplication.translate("Dialog", u"Ne", None))
        self.mfcDgas.setItemText(11, QCoreApplication.translate("Dialog", u"O2", None))
        self.mfcDgas.setItemText(12, QCoreApplication.translate("Dialog", u"C3H8", None))
        self.mfcDgas.setItemText(13, QCoreApplication.translate("Dialog", u"n-C4H10", None))
        self.mfcDgas.setItemText(14, QCoreApplication.translate("Dialog", u"C2H2", None))
        self.mfcDgas.setItemText(15, QCoreApplication.translate("Dialog", u"C2H4", None))
        self.mfcDgas.setItemText(16, QCoreApplication.translate("Dialog", u"i-C2H10", None))
        self.mfcDgas.setItemText(17, QCoreApplication.translate("Dialog", u"Kr", None))
        self.mfcDgas.setItemText(18, QCoreApplication.translate("Dialog", u"Xe", None))
        self.mfcDgas.setItemText(19, QCoreApplication.translate("Dialog", u"SF6", None))
        self.mfcDgas.setItemText(20, QCoreApplication.translate("Dialog", u"C-25", None))
        self.mfcDgas.setItemText(21, QCoreApplication.translate("Dialog", u"C-10", None))
        self.mfcDgas.setItemText(22, QCoreApplication.translate("Dialog", u"C-8", None))
        self.mfcDgas.setItemText(23, QCoreApplication.translate("Dialog", u"C-2", None))
        self.mfcDgas.setItemText(24, QCoreApplication.translate("Dialog", u"C-75", None))
        self.mfcDgas.setItemText(25, QCoreApplication.translate("Dialog", u"A-75", None))
        self.mfcDgas.setItemText(26, QCoreApplication.translate("Dialog", u"A-25", None))
        self.mfcDgas.setItemText(27, QCoreApplication.translate("Dialog", u"A1025", None))
        self.mfcDgas.setItemText(28, QCoreApplication.translate("Dialog", u"Star29", None))
        self.mfcDgas.setItemText(29, QCoreApplication.translate("Dialog", u"P-5", None))

        self.label_5.setText(QCoreApplication.translate("Dialog", u"MFC D:", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Driver gas injection", None))
        self.openS1.setText(QCoreApplication.translate("Dialog", u"Open", None))
        self.closeS1.setText(QCoreApplication.translate("Dialog", u"Close", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Fuel injection", None))
        self.closeS2.setText(QCoreApplication.translate("Dialog", u"Close", None))
        self.openS2.setText(QCoreApplication.translate("Dialog", u"Open", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Oxidizer and Dilutent Inection", None))
        self.closeS3.setText(QCoreApplication.translate("Dialog", u"Close", None))
        self.openS3.setText(QCoreApplication.translate("Dialog", u"Open", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Purge *default open*", None))
        self.openS4.setText(QCoreApplication.translate("Dialog", u"Open", None))
        self.closeS4.setText(QCoreApplication.translate("Dialog", u"Close", None))
        self.closeS5.setText(QCoreApplication.translate("Dialog", u"Close", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Static presure sensor protection", None))
        self.openS5.setText(QCoreApplication.translate("Dialog", u"Open", None))
        self.closeS7.setText(QCoreApplication.translate("Dialog", u"Close", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Exhaust *default open*", None))
        self.openS6.setText(QCoreApplication.translate("Dialog", u"Open", None))
        self.closeS7_2.setText(QCoreApplication.translate("Dialog", u"Close", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Vaccuum valve", None))
        self.openS7.setText(QCoreApplication.translate("Dialog", u"Open", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Setpoint:", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Setpoint:", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Setpoint:", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Setpoint:", None))
        self.mfcAsetpoint.setPlainText(QCoreApplication.translate("Dialog", u"0.0\n"
"", None))
        self.mfcBsetpoint.setPlainText(QCoreApplication.translate("Dialog", u"0.0\n"
"", None))
        self.mfcCsetpoint.setPlainText(QCoreApplication.translate("Dialog", u"0.0\n"
"", None))
        self.mfcDsetpoint.setPlainText(QCoreApplication.translate("Dialog", u"0.0\n"
"", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"SLPM", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"SLPM", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"SLPM", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"SLPM", None))
        self.updatesetpoints.setText(QCoreApplication.translate("Dialog", u"Update Setpoints", None))
        self.resetmfc.setText(QCoreApplication.translate("Dialog", u"Reset flow", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"Solenoid States:", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"Static Pressure", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Transient Pressure", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Pressure Monitors:", None))
        self.testautomation.setText(QCoreApplication.translate("Dialog", u"Begin Testing", None))
        self.purge.setText(QCoreApplication.translate("Dialog", u"PURGE", None))

if __name__ == "__main__":
    import sys
    from PySide6.QtWidgets import QApplication, QDialog

    app = QApplication(sys.argv)
    dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec())